name: Lint and Fix Python Code

on:
  push:
    branches:
      - main  # Run on pushes to main
  pull_request:
    branches:
      - main  # Run on pull requests targeting main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use the version of Python you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 autopep8  # Install Flake8 and autopep8

      - name: Read .flake8 configuration
        run: |
          if [ -f .flake8 ]; then
            echo "Contents of .flake8:"
            cat .flake8
          else
            echo ".flake8 file not found."
          fi

      - name: Run flake8
        id: lint
        run: |
          flake8 . --max-line-length=500 --extend-ignore=E203,W503 > lint_report.txt || true
          echo "::set-output name=lint_report::$(cat lint_report.txt)"
      
      - name: Auto-fix code
        run: |
          autopep8 --in-place --aggressive --aggressive .
          flake8 . --max-line-length=500 --extend-ignore=E203,W503 > lint_report_after.txt || true
          echo "::set-output name=lint_report_after::$(cat lint_report_after.txt)"

      - name: Check for linting issues
        run: |
          if [[ -s lint_report_after.txt ]]; then
            echo "Linting issues found after auto-fix:"
            cat lint_report_after.txt
            exit 1
          else
            echo "No linting issues found after auto-fix."
          fi

      - name: Commit and push changes
        if: success() && steps.lint.outputs.lint_report_after != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .  # Add the files that have been modified
          git commit -m "Auto-fix linting issues"
          git push
