name: Lint and Fix Python Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 autopep8

      - name: Read .flake8 configuration
        run: |
          if [ -f .flake8 ]; then
            echo "Contents of .flake8:"
            cat .flake8
          else
            echo ".flake8 file not found."
          fi

      - name: Run flake8
        id: lint
        run: |
          flake8 . --max-line-length=500 --extend-ignore=E501,W503 > lint_report.txt || true
          echo "::set-output name=lint_report::$(cat lint_report.txt)"
      
      - name: Auto-fix code
        run: |
          find . -name '*.py' -exec autopep8 --in-place --aggressive --aggressive {} +
          flake8 . --max-line-length=500 --extend-ignore=E501,W503 > lint_report_after.txt || true
          echo "::set-output name=lint_report_after::$(cat lint_report_after.txt)"

      - name: Commit and push changes if there are any
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add '*.py'
          
          if ! git diff --cached --quiet; then
            git commit -m "Auto-fix linting issues"
            git push
          else
            echo "No changes to commit"
          fi
