name: Secret Scanning

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run TruffleHog Secret Scanner
        uses: trufflesecurity/trufflehog  # Update to the latest version