name: Test Python 3.12 Requirements

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main  

jobs:
  test-requirements:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.12']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify installation
        run: |
          # This can be any command that checks for successful installation, e.g., running tests
          python -c "import pkgutil; print('All packages loaded successfully')" || exit 1

      - name: Report Success
        run: echo "Python 3.12 requirements check completed successfully!"
